"""
constants.py

Backward-compatibility shim. The real definitions now live in
waf_core/constants.py (framework-independent, single source of
truth). This module re-exports them so any existing `from
waf.constants import X` keeps working unchanged.
"""

from waf_core.constants import *  # noqa: F401,F403
from waf_core.constants import (
    ALLOW, BLOCK, LOW, MEDIUM, HIGH, CRITICAL, SEVERITY_LEVELS,
    HTTP_OK, HTTP_FORBIDDEN, HTTP_BAD_REQUEST, HTTP_UNAUTHORIZED,
    HTTP_NOT_FOUND, HTTP_INTERNAL_SERVER_ERROR,
    MIN_RISK_SCORE, MAX_RISK_SCORE, DEFAULT_BLOCK_THRESHOLD,
    BLOCK_MESSAGE, ALLOW_MESSAGE,
    UNKNOWN_ATTACK, UNKNOWN_RULE, UNKNOWN_DETECTOR,
    DEFAULT_ATTACK_SCORE, DEFAULT_SEVERITY,
    SQL_INJECTION, XSS, COMMAND_INJECTION, PATH_TRAVERSAL,
    FILE_INCLUSION, MALICIOUS_UPLOAD, BAD_USER_AGENT, RATE_LIMIT, OTHER,
    HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE,
    HTTP_OPTIONS, HTTP_HEAD,
    ACCESS_LOGGER, ATTACK_LOGGER, SYSTEM_LOGGER,
    HEADER_USER_AGENT, HEADER_REFERER, HEADER_HOST, HEADER_COOKIE,
    HEADER_CONTENT_TYPE,
    UNKNOWN_IP, DEFAULT_ENCODING, VERSION,
)
