# Generated by Django 5.0.6 on 2026-07-23 06:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='The blocked IP address.', unique=True)),
                ('reason', models.TextField(blank=True, help_text='Why this IP was blocked (e.g. rule name, attack type).')),
                ('blocked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the block lifts. Leave blank for a permanent block.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this block is currently in effect.')),
                ('attack_count', models.PositiveIntegerField(default=1, help_text='Number of attacks attributed to this IP while blocked.')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('detection_count', models.PositiveIntegerField(default=0)),
                ('false_positive_count', models.PositiveIntegerField(default=0)),
                ('last_detection', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detector Statistic',
                'verbose_name_plural': 'Detector Statistics',
                'ordering': ['-detection_count'],
            },
        ),
        migrations.CreateModel(
            name='RuleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rule Statistic',
                'verbose_name_plural': 'Rule Statistics',
                'ordering': ['-trigger_count'],
            },
        ),
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Source IP address of the request.')),
                ('url', models.CharField(help_text='Request path/URL that triggered detection.', max_length=2048)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], help_text='HTTP method of the request.', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the attack was detected.')),
                ('payload', models.JSONField(blank=True, help_text='Raw request body/params captured at detection time.', null=True)),
                ('headers', models.JSONField(blank=True, help_text='Request headers captured at detection time.', null=True)),
                ('attack_type', models.CharField(choices=[('sql_injection', 'SQL Injection'), ('xss', 'Cross-Site Scripting (XSS)'), ('html_injection', 'HTML Injection'), ('file_upload', 'File Upload Vulnerability'), ('command_injection', 'Command Injection'), ('path_traversal', 'Path Traversal'), ('csrf', 'CSRF'), ('other', 'Other')], db_index=True, help_text='Category of attack (see AttackType for known values).', max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=0, help_text='Normalized risk score (0-100) assigned by the decision engine.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rule_triggered', models.CharField(blank=True, db_index=True, help_text='Name/ID of the specific rule that matched.', max_length=150)),
                ('detector_name', models.CharField(blank=True, db_index=True, help_text='Which detector module flagged this request.', max_length=150)),
                ('user_agent', models.TextField(blank=True)),
                ('blocked', models.BooleanField(db_index=True, default=False, help_text='Whether the decision engine blocked this request.')),
                ('response_code', models.PositiveSmallIntegerField(blank=True, help_text='HTTP status code ultimately returned to the client.', null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Attack Log',
                'verbose_name_plural': 'Attack Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='waf_attackl_timesta_61b6d9_idx'), models.Index(fields=['ip_address', '-timestamp'], name='waf_attackl_ip_addr_ac8e5d_idx'), models.Index(fields=['attack_type', '-timestamp'], name='waf_attackl_attack__ff91b4_idx'), models.Index(fields=['severity', '-timestamp'], name='waf_attackl_severit_39c5af_idx')],
            },
        ),
    ]
